packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/expo': ^1.4.7
  '@orpc/client': ^1.12.2
  '@orpc/openapi': 1.13.0
  '@orpc/server': ^1.12.2
  '@orpc/tanstack-query': ^1.12.2
  '@orpc/zod': 1.13.0
  '@tanstack/react-query': ^5.90.12
  better-auth: ^1.4.7
  dotenv: ^17.2.2
  hono: ^4.8.2
  zod: ^4.1.13
